mod base_syntax;
mod control_syntax;
mod enum_syntax;
mod fn_syntax;
mod guess_num;
mod owner_ship;
mod package_syntax;
mod struct_syntax;
mod use_syntax;
mod vector_syntax;
mod string_syntax;
mod hashmap_syntax;
mod panic_syntax;
mod type_syntax;
mod trait_syntax;
mod life_cycle;
mod test;
mod closure;
mod iter_syntax;
mod point_syntax;
mod concurrent_parallel;
mod oop;
mod patterns_matching;

fn main() {
    // guess_num::start();
    // base_syntax::start();
    // fn_syntax::start();
    // control_syntax::start();
    // owner_ship::start();
    // struct_syntax::start();
    // enum_syntax::start();
    // use_syntax::start();
    // vector_syntax::start();
    // string_syntax::start();
    // hashmap_syntax::start();
    // panic_syntax::start();
    // type_syntax::start();
    // trait_syntax::start();
    // life_cycle::start();
    // test::start();
    // closure::start();
    // iter_syntax::start();
    // point_syntax::start();
    // concurrent_parallel::start();
    // oop::start();
    patterns_matching::start();
}
