[package]
name = "module1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
module2 = { path = "../module2" }
rand = "0.3.14"
